version: "3"

vars:
  PKGNAME:
    sh: "sed -n 's/Package: *\\([^ ]*\\)/\\1/p' DESCRIPTION"
  PKGVERS:
    sh: "sed -n 's/Version: *\\([^ ]*\\)/\\1/p' DESCRIPTION"
  PKGSRC:
    sh: "basename $(pwd)"

tasks:
  default:
    deps: [install]

  clean:
    cmds:
      - rm -rf src/*.o src/*.so

  docs:
    cmds:
      - 'Rscript -e ''devtools::document(roclets = c("rd", "collate", "namespace"))'''

  compile-attributes:
    cmds:
      - "Rscript -e 'Rcpp::compileAttributes()'"

  build:
    deps: [docs, compile-attributes]
    cmds:
      - cd .. && R CMD build --no-manual {{.PKGSRC}} --no-build-vignettes

  build-cran:
    deps: [compile-attributes]
    cmds:
      - cd .. && R CMD build {{.PKGSRC}}

  install:
    deps: [compile-attributes]
    cmds:
      - cd .. && R CMD INSTALL --no-multiarch --with-keep.source {{.PKGNAME}}

  clean-install:
    deps: [compile-attributes]
    cmds:
      - R CMD INSTALL --preclean --no-multiarch --with-keep.source {{.PKGNAME}}

  check:
    deps: [compile-attributes]
    cmds:
      - "Rscript -e 'devtools::check()'"

  test:
    deps: [compile-attributes]
    cmds:
      - "Rscript -e 'devtools::test()'"

  vignettes:
    cmds:
      - "Rscript -e 'devtools::build_vignettes()'"
